apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: hash-model-ids
  annotations:
    github.com/project-slug: yourparkingspace/hash-model-ids
spec:
  type: service
  lifecycle: production
  owner: parkmaven
